version: "3.0"
services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    volumes:
      - ./src:/src/
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - elastic
    ports:
      - 9200:9200

  kibana:
    container_name: kibana-container
    image: docker.elastic.co/kibana/kibana:8.11.1
    volumes:
      - ./src:/src/
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - elastic
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

networks:
  elastic:
    driver: bridge
